# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

import os
import subprocess

project = 'Kdenlive Manual'
description = 'The official Kdenlive Documentation'
copyright = 'licensed under the  <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons License SA 4.0</a> unless stated otherwise'
author = 'Kdenlive Community'

# The full version, including alpha/beta/rc tags
release = '24.08'

# Get the git description if possible, to put it in the footer.

try:
    gitcommitfriendly = subprocess.check_output(["git", "describe", "--always"]).decode("utf-8").strip()
except subprocess.CalledProcessError as exc:
    gitcommitfriendly = None


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
   # Workaround for https://github.com/readthedocs/sphinx_rtd_theme/issues/1452
   "sphinxcontrib.jquery",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['resources/templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['build', 'Thumbs.db', '.DS_Store', '.venv*']
html_extra_path = ['404handler.php'] # bring our 404 handler in

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# languages to exclude from smartquotes transformation. Requested by catalan translators due l':ref:`<crop_tool>` getting rendered as l"crop tool.
smartquotes_excludes = {'languages':[
                                    'ja',
                                    'ca',
                                    'fr'
                                    ],
                        'builders': [
                                    'man',
                                    'text'
                                    ]
                        }

# This reStructuredText will be included at the begin of every source file.
#rst_prolog = ""
# This reStructuredText will be included at the end of every source file.
rst_epilog = """
.. |add-subtitle| image:: /images/icons/add-subtitle.svg
   :width: 22px
   :class: no-scaled-link

.. |adjustlevels| image:: /images/icons/adjustlevels.svg
   :width: 22px
   :class: no-scaled-link

.. |align-horizontal-center| image:: /images/icons/align-horizontal-center.svg
   :width: 22px
   :class: no-scaled-link

.. |align-horizontal-left| image:: /images/icons/align-horizontal-left.svg
   :width: 22px
   :class: no-scaled-link

.. |align-horizontal-right| image:: /images/icons/align-horizontal-right.svg
   :width: 22px
   :class: no-scaled-link

.. |align-vertical-top| image:: /images/icons/align-vertical-top.svg
   :width: 22px
   :class: no-scaled-link

.. |align-vertical-center| image:: /images/icons/align-vertical-center.svg
   :width: 22px
   :class: no-scaled-link

.. |align-vertical-bottom| image:: /images/icons/align-vertical-bottom.svg
   :width: 22px
   :class: no-scaled-link

.. |application-menu| image:: /images/icons/application-menu.svg
   :width: 22px
   :class: no-scaled-link

.. |bookmark| image:: /images/icons/bookmarks.svg
   :width: 22px
   :class: no-scaled-link

.. |color-picker| image:: /images/icons/color-picker.svg
   :width: 22px
   :class: no-scaled-link

.. |composite-track-preview| image:: /images/icons/composite-track-preview.svg
   :width: 22px
   :class: no-scaled-link

.. |configure| image:: /images/icons/configure.svg
   :width: 22px
   :class: no-scaled-link

.. |discreet| image:: /images/icons/discrete.svg
   :width: 22px
   :class: no-scaled-link

.. |distribute-horizontal| image:: /images/icons/distribute-horizontal.svg
   :width: 22px
   :class: no-scaled-link

.. |document-edit| image:: /images/icons/document-edit.svg
   :width: 22px
   :class: no-scaled-link

.. |document-export| image:: /images/icons/document-export.svg
   :width: 22px
   :class: no-scaled-link

.. |document-import| image:: /images/icons/document-import.svg
   :width: 22px
   :class: no-scaled-link

.. |document-new| image:: /images/icons/document-new.svg
   :width: 22px
   :class: no-scaled-link

.. |document-open| image:: /images/icons/document-open.svg
   :width: 22px
   :class: no-scaled-link

.. |document-save| image:: /images/icons/document-save.svg
   :width: 22px
   :class: no-scaled-link

.. |document-save-as| image:: /images/icons/document-save-as.svg
   :width: 22px
   :class: no-scaled-link

.. |document-save-all| image:: /images/icons/document-save-all.svg
   :width: 22px
   :class: no-scaled-link

.. |document-save-as-template| image:: /images/icons/document-save-as-template.svg
   :width: 22px
   :class: no-scaled-link

.. |draw-ellipse| image:: /images/icons/draw-ellipse.svg
   :width: 22px
   :class: no-scaled-link

.. |edit-clear-history| image:: /images/icons/edit-clear-history.svg
   :width: 22px
   :class: no-scaled-link

.. |edit-copy| image:: /images/icons/edit-copy.svg
   :width: 22px
   :class: no-scaled-link

.. |edit-delete| image:: /images/icons/edit-delete.svg
   :width: 22px
   :class: no-scaled-link

.. |edit-download| image:: /images/icons/edit-download.svg
   :width: 22px
   :class: no-scaled-link

.. |edit-mode| image:: /images/icons/kdenlive-edit-mode.svg
   :width: 22px
   :class: no-scaled-link

.. |edit-paste| image:: /images/icons/edit-paste.svg
   :width: 22px
   :class: no-scaled-link

.. |edit-select-all| image:: /images/icons/edit-select-all.svg
   :width: 22px
   :class: no-scaled-link

.. |edit-select-none| image:: /images/icons/edit-select-none.svg
   :width: 22px
   :class: no-scaled-link

.. |favorite| image:: /images/icons/favorite.svg
   :width: 22px
   :class: no-scaled-link

.. |ffwd| image:: /images/icons/media-seek-forward.svg
   :width: 22px
   :class: no-scaled-link

.. |folder-new| image:: /images/icons/folder-new.svg
   :width: 22px
   :class: no-scaled-link

.. |format-justify-center| image:: /images/icons/format-justify-center.svg
   :width: 22px
   :class: no-scaled-link

.. |format-justify-left| image:: /images/icons/format-justify-left.svg
   :width: 22px
   :class: no-scaled-link

.. |format-justify-right| image:: /images/icons/format-justify-right.svg
   :width: 22px
   :class: no-scaled-link

.. |format-text-italic| image:: /images/icons/format-text-italic.svg
   :width: 22px
   :class: no-scaled-link

.. |format-text-underline| image:: /images/icons/format-text-underline.svg
   :width: 22px
   :class: no-scaled-link

.. |go-down| image:: /images/icons/go-down.svg
   :width: 22px
   :class: no-scaled-link

.. |go-next| image:: /images/icons/go-next.svg
   :width: 22px
   :class: no-scaled-link

.. |go-up| image:: /images/icons/go-up.svg
   :width: 22px
   :class: no-scaled-link

.. |hint| image:: /images/icons/hint.svg
   :width: 22px
   :class: no-scaled-link

.. |insert-image| image:: /images/icons/insert-image.svg
   :width: 22px
   :class: no-scaled-link

.. |insert-text| image:: /images/icons/insert-text.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-add-clip| image:: /images/icons/kdenlive-add-clip.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-audio| image:: /images/icons/kdenlive-audio.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-hide-audio| image:: /images/icons/kdenlive-hide-audio.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-hide-video| image:: /images/icons/kdenlive-hide-video.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-insert-rect| image:: /images/icons/kdenlive-insert-rect.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-insert-unicode| image:: /images/icons/kdenlive-insert-unicode.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-lock| image:: /images/icons/track-locked.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-razor| image:: /images/icons/edit-cut.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-ripple| image:: /images/icons/kdenlive-ripple.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-select| image:: /images/icons/kdenlive-select-tool.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-select-images| image:: /images/icons/kdenlive-select-images.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-select-texts| image:: /images/icons/kdenlive-select-texts.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-show-video| image:: /images/icons/kdenlive-show-video.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-show-audio| image:: /images/icons/view-media-visualization.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-show-markers| image:: /images/icons/kdenlive-show-markers.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-slip| image:: /images/icons/kdenlive-slip.svg
   :width: 22px
   :class: no-scaled-link

.. |kdenlive-spacer| image:: /images/icons/distribute-horizontal.svg
   :width: 22px
   :class: no-scaled-link

.. |keyframe| image:: /images/icons/keyframe.svg
   :width: 22px
   :class: no-scaled-link

.. |keyframe-add| image:: /images/icons/keyframe-add.svg
   :width: 22px
   :class: no-scaled-link

.. |keyframe-disable| image:: /images/icons/keyframe-disable.svg
   :width: 22px
   :class: no-scaled-link

.. |keyframe-next| image:: /images/icons/keyframe-next.svg
   :width: 22px
   :class: no-scaled-link

.. |keyframe-previous| image:: /images/icons/keyframe-previous.svg
   :width: 22px
   :class: no-scaled-link

.. |keyframe-remove| image:: /images/icons/keyframe-remove.svg
   :width: 22px
   :class: no-scaled-link

.. |keyframe-record| image:: /images/icons/keyframe-record.svg
   :width: 22px
   :class: no-scaled-link

.. |linear| image:: /images/icons/linear.svg
   :width: 22px
   :class: no-scaled-link

.. |list-add| image:: /images/icons/list-add.svg
   :width: 22px
   :class: no-scaled-link

.. |list-remove| image:: /images/icons/list-remove.svg
   :width: 22px
   :class: no-scaled-link

.. |media-record| image:: /images/icons/media-record.svg
   :width: 22px
   :class: no-scaled-link

.. |network-server-database| image:: /images/icons/network-server-database.svg
   :width: 22px
   :class: no-scaled-link

.. |object-order-back| image:: /images/icons/object-order-back.svg
   :width: 22px
   :class: no-scaled-link

.. |object-order-front| image:: /images/icons/object-order-front.svg
   :width: 22px
   :class: no-scaled-link

.. |object-order-lower| image:: /images/icons/object-order-lower.svg
   :width: 22px
   :class: no-scaled-link

.. |object-order-raise| image:: /images/icons/object-order-raise.svg
   :width: 22px
   :class: no-scaled-link

.. |play| image:: /images/icons/media-playback-start.svg
   :width: 22px
   :class: no-scaled-link

.. |preview-add-zone| image:: /images/icons/preview-add-zone.svg
   :width: 22px
   :class: no-scaled-link

.. |preview-remove-all| image:: /images/icons/preview-remove-all.svg
   :width: 22px
   :class: no-scaled-link

.. |preview-remove-zone| image:: /images/icons/preview-remove-zone.svg
   :width: 22px
   :class: no-scaled-link

.. |preview-render-off| image:: /images/icons/preview-render-off.svg
   :width: 22px
   :class: no-scaled-link

.. |preview-render-on| image:: /images/icons/preview-render-on.svg
   :width: 22px
   :class: no-scaled-link

.. |rewind| image:: /images/icons/media-seek-backward.svg
   :width: 22px
   :class: no-scaled-link

.. |select-rectangular| image:: /images/icons/select-rectangular.svg
   :width: 22px
   :class: no-scaled-link

.. |smooth| image:: /images/icons/smooth.svg
   :width: 22px
   :class: no-scaled-link

.. |snap| image:: /images/icons/snap.svg
   :width: 22px
   :class: no-scaled-link

.. |switch to cure editor view| image:: /images/icons/tool_curve.svg
   :width: 22px
   :class: no-scaled-link

.. |switch to timeline view| image:: /images/icons/tool-measure.svg
   :width: 22px
   :class: no-scaled-link

.. |tag| image:: /images/icons/kdenlive-tag.svg
   :width: 22px
   :class: no-scaled-link

.. |timeline-extract| image:: /images/icons/timeline-extract.svg
   :width: 22px
   :class: no-scaled-link

.. |timeline-insert| image:: /images/icons/timeline-insert.svg
   :width: 22px
   :class: no-scaled-link

.. |timeline-lift| image:: /images/icons/timeline-lift.svg
   :width: 22px
   :class: no-scaled-link

.. |timeline-overwrite| image:: /images/icons/timeline-overwrite.svg
   :width: 22px
   :class: no-scaled-link

.. |timeline-use-zone-off| image:: /images/icons/timeline-use-zone-off.svg
   :width: 22px
   :class: no-scaled-link

.. |timeline-use-zone-on| image:: /images/icons/timeline-use-zone-on.svg
   :width: 22px
   :class: no-scaled-link

.. |track-effect| image:: /images/icons/tools-wizard.svg
   :width: 22px
   :class: no-scaled-link

.. |track-locked| image:: /images/icons/track-locked.svg
   :width: 22px
   :class: no-scaled-link

.. |track-unlocked| image:: /images/icons/track-unlocked.svg
   :width: 22px
   :class: no-scaled-link

.. |transform-move| image:: /images/icons/transform-move.svg
   :width: 22px
   :class: no-scaled-link

.. |transform-move-horizontal| image:: /images/icons/transform-move-horizontal.svg
   :width: 22px
   :class: no-scaled-link

.. |tools-wizard| image:: /images/icons/tools-wizard.svg
   :width: 22px
   :class: no-scaled-link

.. |view-hidden| image:: /images/icons/view-hidden.svg
   :width: 22px
   :class: no-scaled-link

.. |view-filter| image:: /images/icons/view-filter.svg
   :width: 22px
   :class: no-scaled-link

.. |view-fullscreen| image:: /images/icons/view-fullscreen.svg
   :width: 22px
   :class: no-scaled-link

.. |view-grid| image:: /images/icons/drag-surface.svg
   :width: 22px
   :class: no-scaled-link

.. |view-media-equalizer| image:: /images/icons/view-media-equalizer.svg
   :width: 22px
   :class: no-scaled-link

.. |view-preview| image:: /images/icons/view-preview.svg
   :width: 22px
   :class: no-scaled-link

.. |view-refresh| image:: /images/icons/view-refresh.svg
   :width: 22px
   :class: no-scaled-link

.. |view-right-close| image:: /images/icons/view-right-close.svg
   :width: 22px
   :class: no-scaled-link

.. |view-split-left-right| image:: /images/icons/view-split-left-right.svg
   :width: 22px
   :class: no-scaled-link

.. |view-visible| image:: /images/icons/view-visible.svg
   :width: 22px
   :class: no-scaled-link

.. |visibility| image:: /images/icons/visibility.svg
   :width: 22px
   :class: no-scaled-link

.. |zone-in| image:: /images/icons/zone-in.svg
   :width: 22px
   :class: no-scaled-link

.. |zone-out| image:: /images/icons/zone-out.svg
   :width: 22px
   :class: no-scaled-link

.. |zoom-fit-best| image:: /images/icons/zoom-fit-best.svg
   :width: 22px
   :class: no-scaled-link

.. |zoom-fit-height| image:: /images/icons/zoom-fit-height.svg
   :width: 22px
   :class: no-scaled-link

.. |zoom-fit-width| image:: /images/icons/zoom-fit-width.svg
   :width: 22px
   :class: no-scaled-link

.. |zoom-in| image:: /images/icons/zoom-in.svg
   :width: 22px
   :class: no-scaled-link

.. |zoom-out| image:: /images/icons/zoom-out.svg
   :width: 22px
   :class: no-scaled-link

.. |zoom-original| image:: /images/icons/zoom-original.svg
   :width: 22px
   :class: no-scaled-link

.. |outdated| replace:: The instructions of this section are probably out-dated please help us to improve the documentation! See :ref:`get_involved`

.. |linux| image:: /images/icons/linux.png
   :width: 14px
   :alt: Linux
   :class: no-scaled-link

.. |appimage| image:: /images/icons/kdenlive-appimage_3.svg
   :width: 14px
   :alt: appimage
   :class: no-scaled-link

.. |windows| image:: /images/icons/windows.png
   :width: 14px
   :alt: Windows
   :class: no-scaled-link

.. |apple| image:: /images/icons/apple.png
   :width: 14px
   :alt: MacOS
   :class: no-scaled-link

"""

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#

import sphinx_rtd_theme
html_theme = 'sphinx_rtd_theme' #'alabaster' #'sphinx_rtd_theme' 'insegel'
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

html_theme_options = {
     # Toc options. The maximum depth of the table of contents tree (on the sidebar). Set this to -1 to allow unlimited depth. Set to 5 to see sub-title of https://docs.kdenlive.org/en/user_interface/menu/settings_menu/configure_kdenlive.html
    'navigation_depth': 5,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['resources/static']

html_favicon = 'resources/static/images/favicon.ico'

html_logo = 'resources/static/images/logo-light.svg'

if html_theme == "sphinx_rtd_theme":
    html_css_files = ["css/theme_overrides.css",
                      "css/version_switch.css"]
    html_js_files = ["js/version_switch.js"]

html_context = {
    'build_id': os.getenv('BUILD_NUMBER', None),
    'build_url': os.getenv('BUILD_URL', None),
    'commit' : gitcommitfriendly
}

html_last_updated_fmt = '%Y-%m-%dT%H:%M:%S'

# -- Internationalization Options --------------------------------------------

locale_dirs = ['locale/']   # Where the PO files will be stored at
gettext_compact = False     # optional.
#gettext_additional_targets = ['image', 'index', 'literal-block'] # allows images to be translatable
#figure_language_filename = "{path}{language}/{basename}{ext}"

