# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

import os
import subprocess

project = 'Kdenlive Manual'
description = 'The official Kdenlive Documentation'
copyright = 'licensed under the  <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons License SA 4.0</a> unless stated otherwise'
author = 'Kdenlive Community'

# The full version, including alpha/beta/rc tags
release = '23.04'

# Get the git description if possible, to put it in the footer.

try:
    gitcommitfriendly = subprocess.check_output(["git", "describe", "--always"]).decode("utf-8").strip()
except subprocess.CalledProcessError as exc:
    gitcommitfriendly = None


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['resources/templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['build', 'Thumbs.db', '.DS_Store', '.venv*']
html_extra_path = ['404handler.php'] # bring our 404 handler in

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# languages to exclude from smartquotes transformation. Requested by catalan translators due l':ref:`<crop_tool>` getting rendered as l"crop tool.
smartquotes_excludes = {'languages':[
                                    'ja',
                                    'ca',
                                    'fr'
                                    ],
                        'builders': [
                                    'man',
                                    'text'
                                    ]
                        }

# This reStructuredText will be included at the begin of every source file.
#rst_prolog = ""
# This reStructuredText will be included at the end of every source file.
rst_epilog = """
.. |kdenlive-add-clip| image:: /images/icons/kdenlive-add-clip.svg
   :width: 22px

.. |application-menu| image:: /images/icons/application-menu.svg
   :width: 22px

.. |view-preview| image:: /images/icons/view-preview.svg
   :width: 22px

.. |distribute-horizontal| image:: /images/icons/distribute-horizontal.svg
   :width: 22px

.. |media-record| image:: /images/icons/media-record.svg
   :width: 22px

.. |document-new| image:: /images/icons/document-new.svg
   :width: 22px

.. |document-save-as| image:: /images/icons/document-save-as.svg
   :width: 22px

.. |document-edit| image:: /images/icons/document-edit.svg
   :width: 22px

.. |edit-download| image:: /images/icons/edit-download.svg
   :width: 22px

.. |kdenlive-lock| image:: /images/icons/kdenlive-lock.svg
   :width: 22px

.. |kdenlive-hide-audio| image:: /images/icons/kdenlive-hide-audio.svg
   :width: 22px

.. |kdenlive-hide-video| image:: /images/icons/kdenlive-hide-video.svg
   :width: 22px

.. |tools-wizard| image:: /images/icons/tools-wizard.svg
   :width: 22px

.. |timeline-use-zone-off| image:: /images/icons/timeline-use-zone-off.svg
   :width: 22px

.. |timeline-use-zone-on| image:: /images/icons/timeline-use-zone-on.svg
   :width: 22px

.. |timeline-extract| image:: /images/icons/timeline-extract.svg
   :width: 22px

.. |timeline-insert| image:: /images/icons/timeline-insert.svg
   :width: 22px

.. |timeline-lift| image:: /images/icons/timeline-lift.svg
   :width: 22px

.. |timeline-overwrite| image:: /images/icons/timeline-overwrite.svg
   :width: 22px

.. |add-subtitle| image:: /images/icons/add-subtitle.svg
   :width: 22px

.. |composite-track-preview| image:: /images/icons/composite-track-preview.svg
   :width: 22px

.. |favorite| image:: /images/icons/favorite.svg
   :width: 22px

.. |kdenlive-ripple| image:: /images/icons/kdenlive-ripple.svg
   :width: 22px

.. |kdenlive-slip| image:: /images/icons/kdenlive-slip.svg
   :width: 22px

.. |preview-render-on| image:: /images/icons/preview-render-on.svg
   :width: 22px

.. |view-media-equalizer| image:: /images/icons/view-media-equalizer.svg
   :width: 22px

.. |document-save-all.svg| image:: /images/icons/document-save-all.svg
   :width: 22px

.. |view-right-close.svg| image:: /images/icons/view-right-close.svg
   :width: 22px

.. |view-split-left-right.svg| image:: /images/icons/view-split-left-right.svg
   :width: 22px

.. |hint.svg| image:: /images/icons/hint.svg
   :width: 22px

.. |visibility.svg| image:: /images/icons/visibility.svg
   :width: 22px

.. |keyframe-disable.svg| image:: /images/icons/keyframe-disable.svg
   :width: 22px

.. |keyframe.svg| image:: /images/icons/keyframe.svg
   :width: 22px

.. |adjustlevels.svg| image:: /images/icons/adjustlevels.svg
   :width: 22px

.. |view-refresh.svg| image:: /images/icons/view-refresh.svg
   :width: 22px

.. |document-save-as-template.svg| image:: /images/icons/document-save-as-template.svg
   :width: 22px

.. |edit-delete.svg| image:: /images/icons/edit-delete.svg
   :width: 22px

.. |document-save.svg| image:: /images/icons/document-save.svg
   :width: 22px

.. |keyframe-previous.svg| image:: /images/icons/keyframe-previous.svg
   :width: 22px

.. |keyframe-add.svg| image:: /images/icons/keyframe-add.svg
   :width: 22px

.. |keyframe-next.svg| image:: /images/icons/keyframe-next.svg
   :width: 22px

.. |align-horizontal-center.svg| image:: /images/icons/align-horizontal-center.svg
   :width: 22px

.. |edit-copy.svg| image:: /images/icons/edit-copy.svg
   :width: 22px

.. |edit-paste.svg| image:: /images/icons/edit-paste.svg
   :width: 22px

.. |linear.svg| image:: /images/icons/linear.svg
   :width: 22px

.. |align-horizontal-left.svg| image:: /images/icons/align-horizontal-left.svg
   :width: 22px

.. |align-horizontal-right.svg| image:: /images/icons/align-horizontal-right.svg
   :width: 22px

.. |align-vertical-top.svg| image:: /images/icons/align-vertical-top.svg
   :width: 22px

.. |align-vertical-center.svg| image:: /images/icons/align-vertical-center.svg
   :width: 22px

.. |align-vertical-bottom.svg| image:: /images/icons/align-vertical-bottom.svg
   :width: 22px

.. |zoom-original.svg| image:: /images/icons/zoom-original.svg
   :width: 22px

.. |zoom-fit-best.svg| image:: /images/icons/zoom-fit-best.svg
   :width: 22px

.. |zoom-fit-width.svg| image:: /images/icons/zoom-fit-width.svg
   :width: 22px

.. |zoom-fit-height.svg| image:: /images/icons/zoom-fit-height.svg
   :width: 22px

.. |folder-new.svg| image:: /images/icons/folder-new.svg
   :width: 22px

.. |tag.svg| image:: /images/icons/tag.svg
   :width: 22px

.. |preview-add-zone.svg| image:: /images/icons/preview-add-zone.svg
   :width: 22px

.. |preview-remove-zone.svg| image:: /images/icons/preview-remove-zone.svg
   :width: 22px

.. |preview-remove-all.svg| image:: /images/icons/preview-remove-all.svg
   :width: 22px

.. |zone-in.svg| image:: /images/icons/zone-in.svg
   :width: 22px

.. |zone-out.svg| image:: /images/icons/zone-out.svg
   :width: 22px


.. |Kdenlive_Keyboard_074| image:: /images/Kdenlive_Keyboard_074.svg
   :width: 480px

.. |Kdenlive_Keyboard_074_A4| image:: /images/Kdenlive_Keyboard_074_A4.svg
   :width: 480px

.. |outdated| replace:: The instructions of this section are probably out-dated please help us to improve the documentation! See :ref:`get_involved`

"""

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#

import sphinx_rtd_theme
html_theme = 'sphinx_rtd_theme' #'alabaster' #'sphinx_rtd_theme' 'insegel'
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

html_theme_options = {
     # Toc options. The maximum depth of the table of contents tree (on the sidebar). Set this to -1 to allow unlimited depth.
    'navigation_depth': 6,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['resources/static']

html_favicon = 'resources/static/images/favicon.ico'

html_logo = 'resources/static/images/logo-light.svg'

if html_theme == "sphinx_rtd_theme":
    html_css_files = ["css/theme_overrides.css",
                      "css/version_switch.css"]
    html_js_files = ["js/version_switch.js"]

html_context = {
    'build_id': os.getenv('BUILD_NUMBER', None),
    'build_url': os.getenv('BUILD_URL', None),
    'commit' : gitcommitfriendly
}

html_last_updated_fmt = '%Y-%m-%dT%H:%M:%S'

# -- Internationalization Options --------------------------------------------

locale_dirs = ['locale/']   # Where the PO files will be stored at
gettext_compact = False     # optional.
#gettext_additional_targets = ['image', 'index', 'literal-block'] # allows images to be translatable
#figure_language_filename = "{path}{language}/{basename}{ext}"

