# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'Kdenlive'
description = 'The official Kdenlive Documentation'
copyright = 'licensed under the  <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons License SA 4.0</a> unless stated otherwise'
author = 'Kdenlive Community'

# The full version, including alpha/beta/rc tags
release = '21.12'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['../ressources/templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['../build', 'Thumbs.db', '.DS_Store', '.venv*']
html_extra_path = ['404handler.php'] # bring our 404 handler in

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# This reStructuredText will be included at the begin of every source file.
#rst_prolog = ""
# This reStructuredText will be included at the end of every source file.
rst_epilog = """
.. |kdenlive-add-clip| image:: /images/icons/kdenlive-add-clip.svg
   :width: 22px

"""


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#

import sphinx_rtd_theme
html_theme = 'sphinx_rtd_theme' #'alabaster' #'sphinx_rtd_theme' 'insegel'
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['../ressources/static']

html_favicon = '../ressources/static/images/favicon.ico'

html_logo = '../ressources/static/images/logo-light.svg'

# -- Internationalization Options --------------------------------------------

locale_dirs = ['../locale/']   # Where the PO files will be stored at
gettext_compact = False     # optional.
#gettext_additional_targets = ['image', 'index', 'literal-block'] # allows images to be translatable
#figure_language_filename = "{path}{language}/{basename}{ext}"

